CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS cartdb;
CREATE DATABASE IF NOT EXISTS orderdb;
CREATE DATABASE IF NOT EXISTS inventorydb;

GRANT ALL PRIVILEGES ON userdb.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON cartdb.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON orderdb.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON inventorydb.* TO 'user'@'%';

FLUSH PRIVILEGES;